{
	"name": "CVE-2024-27351",
	"threat_severity": "Moderate",
	"public_date": "2024-03-04T09:00:00Z",
	"bugzilla": {
		"description": "python-django: Potential regular expression denial-of-service in django.utils.text.Truncator.words()",
		"id": "2266045",
		"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2266045"
	},
	"cvss3": {
		"cvss3_base_score": "7.5",
		"cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
		"status": "draft"
	},
	"cwe": "CWE-1333",
	"details": [
		"An inefficient regular expression complexity flaw was found in the Truncator.words function and truncatewords_html filter of Django. This issue may allow an attacker to use a suitably crafted string to cause a denial of service."
	],
	"references": [
		"https://www.cve.org/CVERecord?id=CVE-2024-27351\nhttps://nvd.nist.gov/vuln/detail/CVE-2024-27351\nhttps://www.djangoproject.com/weblog/2024/mar/04/security-releases/"
	],
	"package_state": [
		{
			"cpe": "cpe:/a:redhat:ansible_automation_platform",
			"fix_state": "Not affected",
			"package_name": "ansible-tower",
			"product_name": "Red Hat Ansible Automation Platform 1.2"
		},
		{
			"cpe": "cpe:/a:redhat:ansible_automation_platform:2",
			"fix_state": "Affected",
			"package_name": "automation-controller",
			"product_name": "Red Hat Ansible Automation Platform 2"
		},
		{
			"cpe": "cpe:/a:redhat:ansible_automation_platform:2",
			"fix_state": "Affected",
			"package_name": "python-django",
			"product_name": "Red Hat Ansible Automation Platform 2"
		},
		{
			"cpe": "cpe:/a:redhat:certifications:1::el7",
			"fix_state": "Out of support scope",
			"package_name": "python-django",
			"product_name": "Red Hat Certification for Red Hat Enterprise Linux 7"
		},
		{
			"cpe": "cpe:/a:redhat:certifications:1::el8",
			"fix_state": "Affected",
			"package_name": "redhat-certification",
			"product_name": "Red Hat Certification for Red Hat Enterprise Linux 8"
		},
		{
			"cpe": "cpe:/a:redhat:certifications:1::el9",
			"fix_state": "Affected",
			"package_name": "redhat-certification",
			"product_name": "Red Hat Certification for Red Hat Enterprise Linux 9"
		},
		{
			"cpe": "cpe:/a:redhat:discovery:1.0::el8",
			"fix_state": "Affected",
			"package_name": "discovery/discovery-server-rhel8",
			"product_name": "Red Hat Discovery"
		},
		{
			"cpe": "cpe:/a:redhat:openstack:16.1",
			"fix_state": "Under investigation",
			"package_name": "python-django20",
			"product_name": "Red Hat OpenStack Platform 16.1"
		},
		{
			"cpe": "cpe:/a:redhat:openstack:16.2",
			"fix_state": "Under investigation",
			"package_name": "python-django20",
			"product_name": "Red Hat OpenStack Platform 16.2"
		},
		{
			"cpe": "cpe:/a:redhat:openstack:17.1",
			"fix_state": "Under investigation",
			"package_name": "python-django",
			"product_name": "Red Hat OpenStack Platform 17.1"
		},
		{
			"cpe": "cpe:/a:redhat:satellite:6",
			"fix_state": "Affected",
			"package_name": "python-django",
			"product_name": "Red Hat Satellite 6"
		},
		{
			"cpe": "cpe:/a:redhat:storage:3",
			"fix_state": "Under investigation",
			"package_name": "python-django",
			"product_name": "Red Hat Storage 3"
		},
		{
			"cpe": "cpe:/a:redhat:rhui:4::el8",
			"fix_state": "Affected",
			"package_name": "python-django",
			"product_name": "Red Hat Update Infrastructure 4 for Cloud Providers"
		}
	],
	"upstream_fix": "python-django 3.2.25, python-django 4.2.11, python-django 5.0.3",
	"csaw": false
}
