{
	"name": "CVE-2024-26130",
	"threat_severity": "Important",
	"public_date": "2024-02-21T00:00:00Z",
	"bugzilla": {
		"description": "python-cryptography: NULL pointer dereference with pkcs12.serialize_key_and_certificates when called with a non-matching certificate and private key and an hmac_hash override",
		"id": "2269617",
		"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2269617"
	},
	"cvss3": {
		"cvss3_base_score": "7.5",
		"cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
		"status": "draft"
	},
	"cwe": "CWE-476",
	"details": [
		"cryptography is a package designed to expose cryptographic primitives and recipes to Python developers. Starting in version 38.0.0 and prior to version 42.0.4, if `pkcs12.serialize_key_and_certificates` is called with both a certificate whose public key did not match the provided private key and an `encryption_algorithm` with `hmac_hash` set (via `PrivateFormat.PKCS12.encryption_builder().hmac_hash(...)`, then a NULL pointer dereference would occur, crashing the Python process. This has been resolved in version 42.0.4, the first version in which a `ValueError` is properly raised.",
		"A flaw was discovered in python-cryptography. A NULL pointer dereference can be triggered when a PKCS#12 key and certificate do not match. Specifically, if the pkcs12.serialize_key_and_certificates function is called with a non-matching certificate and private key and an encryption algorithm with hmac_hash set, the Python process may crash, leading to a denial of service."
	],
	"statement": "The vulnerability in python-cryptography that leads to a NULL pointer dereference during the pkcs12.serialize_key_and_certificates function execution is classified as a moderate severity issue. While the vulnerability can result in a denial-of-service (DoS) by crashing the Python process, it requires specific conditions to trigger: a mismatch between the provided certificate's public key and private key, coupled with the use of an encryption algorithm with hmac_hash set.\nThe exploitation of this vulnerability does not directly lead to arbitrary code execution or data leakage. Instead, it causes a controlled termination of the Python process, which, although disruptive, is not as critical as other vulnerabilities that can lead to unauthorized access, data corruption, or code injection. However, it's important to note that denial-of-service conditions can still have operational impacts, disrupting services or causing system instability.\nThis issue does not affect Red Hat Enterprise Linux 6, 7, 8 and 9 as we dont ship the vulnerable code and package version.",
	"references": [
		"https://www.cve.org/CVERecord?id=CVE-2024-26130\nhttps://nvd.nist.gov/vuln/detail/CVE-2024-26130"
	],
	"mitigation": {
		"lang": "en:us",
		"value": "Mitigation for this issue is either not available or the currently available options don't meet the Red Hat Product Security criteria comprising ease of use and deployment, applicability to widespread installation base or stability."
	},
	"package_state": [
		{
			"cpe": "cpe:/a:redhat:ansible_automation_platform:2",
			"fix_state": "Affected",
			"package_name": "python-cryptography",
			"product_name": "Red Hat Ansible Automation Platform 2"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:7",
			"fix_state": "Not affected",
			"package_name": "python-cryptography",
			"product_name": "Red Hat Enterprise Linux 7"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:8",
			"fix_state": "Not affected",
			"package_name": "python39:3.9/python-cryptography",
			"product_name": "Red Hat Enterprise Linux 8"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:8",
			"fix_state": "Not affected",
			"package_name": "python-cryptography",
			"product_name": "Red Hat Enterprise Linux 8"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:9",
			"fix_state": "Not affected",
			"package_name": "python-cryptography",
			"product_name": "Red Hat Enterprise Linux 9"
		},
		{
			"cpe": "cpe:/a:redhat:satellite:6",
			"fix_state": "Affected",
			"package_name": "python-cryptography",
			"product_name": "Red Hat Satellite 6"
		},
		{
			"cpe": "cpe:/a:redhat:rhui:4::el8",
			"fix_state": "Affected",
			"package_name": "python-cryptography",
			"product_name": "Red Hat Update Infrastructure 4 for Cloud Providers"
		}
	],
	"upstream_fix": "cryptography 42.0.4",
	"csaw": false
}
