{
	"name": "CVE-2024-6232",
	"threat_severity": "Moderate",
	"public_date": "2024-09-03T13:15:05Z",
	"bugzilla": {
		"description": "python: cpython: tarfile: ReDos via excessive backtracking while parsing header values",
		"id": "2309426",
		"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2309426"
	},
	"cvss3": {
		"cvss3_base_score": "7.5",
		"cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
		"status": "draft"
	},
	"cwe": "CWE-1333",
	"details": [
		"There is a MEDIUM severity vulnerability affecting CPython.\nRegular expressions that allowed excessive backtracking during tarfile.TarFile header parsing are vulnerable to ReDoS via specifically-crafted tar archives.",
		"A regular expression denial of service (ReDos) vulnerability was found in Python's tarfile module. Due to excessive backtracking while tarfile parses headers, an attacker may be able to trigger a denial of service via a specially crafted tar archive."
	],
	"statement": "This vulnerability is classified as moderate severity rather than important because while it does allow for a denial of service (DoS) attack via excessive backtracking in the tarfile module, it does not enable remote code execution or compromise the integrity or confidentiality of data. Exploitation requires an attacker to provide a specially crafted tar archive and relies on the victim's system processing that file, which limits the attack vector.\nVersions of python36:3.6/python36 as shipped with Red Hat Enterprise Linux 8 are marked as 'Not affected' as they just provide \"symlinks\" to the main python3 component, which provides the actual interpreter of the Python programming language.",
	"references": [
		"https://www.cve.org/CVERecord?id=CVE-2024-6232\nhttps://nvd.nist.gov/vuln/detail/CVE-2024-6232\nhttps://github.com/python/cpython/issues/121285\nhttps://github.com/python/cpython/pull/121286\nhttps://mail.python.org/archives/list/security-announce@python.org/thread/JRYFTPRHZRTLMZLWQEUHZSJXNHM4ACTY/"
	],
	"mitigation": {
		"lang": "en:us",
		"value": "Mitigation for this issue is either not available or the currently available options do not meet the Red Hat Product Security criteria comprising ease of use and deployment, applicability to widespread installation base or stability."
	},
	"package_state": [
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:6",
			"fix_state": "Out of support scope",
			"package_name": "python",
			"product_name": "Red Hat Enterprise Linux 6"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:7",
			"fix_state": "Out of support scope",
			"package_name": "python",
			"product_name": "Red Hat Enterprise Linux 7"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:7",
			"fix_state": "Affected",
			"package_name": "python3",
			"product_name": "Red Hat Enterprise Linux 7"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:8",
			"fix_state": "Affected",
			"package_name": "python3",
			"product_name": "Red Hat Enterprise Linux 8"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:8",
			"fix_state": "Affected",
			"package_name": "python3.11",
			"product_name": "Red Hat Enterprise Linux 8"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:8",
			"fix_state": "Affected",
			"package_name": "python3.12",
			"product_name": "Red Hat Enterprise Linux 8"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:8",
			"fix_state": "Not affected",
			"package_name": "python36:3.6/python36",
			"product_name": "Red Hat Enterprise Linux 8"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:8",
			"fix_state": "Not affected",
			"package_name": "python39:3.9/python39",
			"product_name": "Red Hat Enterprise Linux 8"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:9",
			"fix_state": "Affected",
			"package_name": "python3.11",
			"product_name": "Red Hat Enterprise Linux 9"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:9",
			"fix_state": "Affected",
			"package_name": "python3.12",
			"product_name": "Red Hat Enterprise Linux 9"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:9",
			"fix_state": "Affected",
			"package_name": "python3.9",
			"product_name": "Red Hat Enterprise Linux 9"
		},
		{
			"cpe": "cpe:/a:redhat:enterprise_linux_ai:1",
			"fix_state": "Affected",
			"package_name": "rhelai1/bootc-nvidia-rhel9",
			"product_name": "Red Hat Enterprise Linux AI (RHEL AI)"
		}
	],
	"csaw": false
}
