{
	"bugzilla": {
		"description": "CVE-2017-5601 libarchive: Out of bounds read in lha_read_file_header_1() function",
		"id": "1417912",
		"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1417912"
	},
	"csaw": false,
	"cvss3": {
		"cvss3_base_score": "4.8",
		"cvss3_scoring_vector": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:N/A:L",
		"status": "draft"
	},
	"cwe": "CWE-20->CWE-190->CWE-125",
	"details": [
		"An error in the lha_read_file_header_1() function (archive_read_support_format_lha.c) in libarchive 3.2.2 allows remote attackers to trigger an out-of-bounds read memory access and subsequently cause a crash via a specially crafted archive."
	],
	"name": "CVE-2017-5601",
	"package_state": [
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:6",
			"fix_state": "Not affected",
			"package_name": "libarchive",
			"product_name": "Red Hat Enterprise Linux 6"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:7",
			"fix_state": "Will not fix",
			"package_name": "libarchive",
			"product_name": "Red Hat Enterprise Linux 7"
		}
	],
	"public_date": "2017-01-27T00:00:00Z",
	"references": [
		"https://www.cve.org/CVERecord?id=CVE-2017-5601\nhttps://nvd.nist.gov/vuln/detail/CVE-2017-5601"
	],
	"statement": "Red Hat Product Security has rated this issue as having Low security\nimpact. This issue is not currently planned to be addressed in future\nupdates. For additional information, refer to the Issue Severity\nClassification: https://access.redhat.com/security/updates/classification.",
	"threat_severity": "Moderate",
	"upstream_fix": "libarchive 3.3.0"
}
