{
	"name": "CVE-2019-3498",
	"threat_severity": "Low",
	"public_date": "2019-01-07T00:00:00Z",
	"bugzilla": {
		"description": "python-django: Content spoofing via URL path in default 404 page",
		"id": "1663722",
		"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1663722"
	},
	"cvss3": {
		"cvss3_base_score": "4.3",
		"cvss3_scoring_vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:L/A:N",
		"status": "draft"
	},
	"cwe": "CWE-99",
	"details": [
		"In Django 1.11.x before 1.11.18, 2.0.x before 2.0.10, and 2.1.x before 2.1.5, an Improper Neutralization of Special Elements in Output Used by a Downstream Component issue exists in django.views.defaults.page_not_found(), leading to content spoofing (in a 404 error page) if a user fails to recognize that a crafted URL has malicious content."
	],
	"statement": "This issue affects the versions of python-django as shipped with Red Hat Update Infrastructure 3. Even though the Red Hat Update Appliance ships python-django, the application is not accessible by default because of the firewall rules, thus this flaw cannot be used. However, it can be triggered on the Content Delivery Systems.\nRed Hat Satellite is not affected, since python-django is only used on Pulp API, which only returns JSON data.",
	"references": [
		"https://www.cve.org/CVERecord?id=CVE-2019-3498\nhttps://nvd.nist.gov/vuln/detail/CVE-2019-3498\nhttps://www.djangoproject.com/weblog/2019/jan/04/security-releases/"
	],
	"package_state": [
		{
			"cpe": "cpe:/a:redhat:ceph_storage:2",
			"fix_state": "Affected",
			"package_name": "python-django",
			"product_name": "Red Hat Ceph Storage 2"
		},
		{
			"cpe": "cpe:/a:redhat:ceph_storage:3",
			"fix_state": "Will not fix",
			"package_name": "python-django",
			"product_name": "Red Hat Ceph Storage 3"
		},
		{
			"cpe": "cpe:/a:redhat:certifications:1::el7",
			"fix_state": "Affected",
			"package_name": "python-django",
			"product_name": "Red Hat Certification for Red Hat Enterprise Linux 7"
		},
		{
			"cpe": "cpe:/a:redhat:openstack:10",
			"fix_state": "Will not fix",
			"package_name": "python-django",
			"product_name": "Red Hat OpenStack Platform 10 (Newton)"
		},
		{
			"cpe": "cpe:/a:redhat:openstack:13",
			"fix_state": "Will not fix",
			"package_name": "python-django",
			"product_name": "Red Hat OpenStack Platform 13 (Queens)"
		},
		{
			"cpe": "cpe:/a:redhat:openstack:14",
			"fix_state": "Will not fix",
			"package_name": "python-django",
			"product_name": "Red Hat OpenStack Platform 14 (Rocky)"
		},
		{
			"cpe": "cpe:/a:redhat:openstack:8",
			"fix_state": "Will not fix",
			"impact": "low",
			"package_name": "python-django",
			"product_name": "Red Hat OpenStack Platform 8 (Liberty)"
		},
		{
			"cpe": "cpe:/a:redhat:openstack-optools:8",
			"fix_state": "Will not fix",
			"impact": "low",
			"package_name": "python-django",
			"product_name": "Red Hat OpenStack Platform 8 (Liberty) Operational Tools"
		},
		{
			"cpe": "cpe:/a:redhat:openstack:9",
			"fix_state": "Will not fix",
			"package_name": "python-django",
			"product_name": "Red Hat OpenStack Platform 9 (Mitaka)"
		},
		{
			"cpe": "cpe:/a:redhat:openstack-optools:9",
			"fix_state": "Will not fix",
			"package_name": "python-django",
			"product_name": "Red Hat OpenStack Platform 9 (Mitaka) Operational Tools"
		},
		{
			"cpe": "cpe:/a:redhat:satellite:6",
			"fix_state": "Not affected",
			"package_name": "python-django",
			"product_name": "Red Hat Satellite 6"
		},
		{
			"cpe": "cpe:/a:redhat:storage:3",
			"fix_state": "Will not fix",
			"package_name": "python-django",
			"product_name": "Red Hat Storage 3"
		},
		{
			"cpe": "cpe:/a:rhel_sam:1",
			"fix_state": "Will not fix",
			"package_name": "Django",
			"product_name": "Red Hat Subscription Asset Manager"
		},
		{
			"cpe": "cpe:/a:redhat:rhui:3",
			"fix_state": "Will not fix",
			"package_name": "python-django",
			"product_name": "Red Hat Update Infrastructure 3 for Cloud Providers"
		}
	],
	"upstream_fix": "python-django 2.0.10, python-django 1.11.18, python-django 2.1.5",
	"csaw": false
}
