{
	"affected_release": [
		{
			"advisory": "RHSA-2020:1810",
			"cpe": "cpe:/a:redhat:enterprise_linux:8",
			"package": "sqlite-0:3.26.0-6.el8",
			"product_name": "Red Hat Enterprise Linux 8",
			"release_date": "2020-04-28T00:00:00Z"
		},
		{
			"advisory": "RHSA-2020:1810",
			"cpe": "cpe:/o:redhat:enterprise_linux:8",
			"package": "sqlite-0:3.26.0-6.el8",
			"product_name": "Red Hat Enterprise Linux 8",
			"release_date": "2020-04-28T00:00:00Z"
		}
	],
	"bugzilla": {
		"description": "heap out-of-bound read in function rtreenode()",
		"id": "1716881",
		"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1716881"
	},
	"csaw": false,
	"cvss3": {
		"cvss3_base_score": "7.5",
		"cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
		"status": "verified"
	},
	"cwe": "CWE-125",
	"details": [
		"SQLite3 from 3.6.0 to and including 3.27.2 is vulnerable to heap out-of-bound read in the rtreenode() function when handling invalid rtree tables."
	],
	"name": "CVE-2019-8457",
	"package_state": [
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:5",
			"fix_state": "Not affected",
			"package_name": "sqlite",
			"product_name": "Red Hat Enterprise Linux 5"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:6",
			"fix_state": "Out of support scope",
			"package_name": "sqlite",
			"product_name": "Red Hat Enterprise Linux 6"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:7",
			"fix_state": "Will not fix",
			"package_name": "sqlite",
			"product_name": "Red Hat Enterprise Linux 7"
		}
	],
	"public_date": "2019-03-20T00:00:00Z",
	"references": [
		"https://www.cve.org/CVERecord?id=CVE-2019-8457\nhttps://nvd.nist.gov/vuln/detail/CVE-2019-8457"
	],
	"threat_severity": "Moderate",
	"upstream_fix": "sqlite 3.28.0"
}
