{
	"affected_release": [
		{
			"advisory": "RHSA-2021:4702",
			"cpe": "cpe:/a:redhat:satellite:6.10::el7",
			"package": "python-ecdsa-0:0.13.3-2.el7pc",
			"product_name": "Red Hat Satellite 6.10 for RHEL 7",
			"release_date": "2021-11-16T00:00:00Z"
		},
		{
			"advisory": "RHSA-2021:4702",
			"cpe": "cpe:/a:redhat:satellite_capsule:6.10::el7",
			"package": "python-ecdsa-0:0.13.3-2.el7pc",
			"product_name": "Red Hat Satellite 6.10 for RHEL 7",
			"release_date": "2021-11-16T00:00:00Z"
		}
	],
	"bugzilla": {
		"description": "CVE-2019-14853 python-ecdsa: Unexpected and  undocumented exceptions during signature decoding",
		"id": "1758704",
		"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1758704"
	},
	"csaw": false,
	"cvss3": {
		"cvss3_base_score": "3.7",
		"cvss3_scoring_vector": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:L",
		"status": "verified"
	},
	"cwe": "CWE-391",
	"details": [
		"An error-handling flaw was found in python-ecdsa before version 0.13.3. During signature decoding, malformed DER signatures could raise unexpected exceptions (or no exceptions at all), which could lead to a denial of service.",
		"An error-handling flaw was found in python-ecdsa.  During signature decoding, malformed DER signatures could raise unexpected exceptions (or no exceptions at all), which could lead to a denial of service."
	],
	"name": "CVE-2019-14853",
	"package_state": [
		{
			"cpe": "cpe:/a:redhat:cloudforms_managementengine:5",
			"fix_state": "Not affected",
			"package_name": "python-ecdsa",
			"product_name": "CloudForms Management Engine 5"
		},
		{
			"cpe": "cpe:/a:redhat:ceph_storage:2",
			"fix_state": "Will not fix",
			"package_name": "python-ecdsa",
			"product_name": "Red Hat Ceph Storage 2"
		},
		{
			"cpe": "cpe:/a:redhat:openstack:10",
			"fix_state": "Will not fix",
			"package_name": "python-ecdsa",
			"product_name": "Red Hat OpenStack Platform 10 (Newton)"
		},
		{
			"cpe": "cpe:/a:redhat:openstack:13",
			"fix_state": "Will not fix",
			"package_name": "python-ecdsa",
			"product_name": "Red Hat OpenStack Platform 13 (Queens)"
		},
		{
			"cpe": "cpe:/a:redhat:openstack:14",
			"fix_state": "Will not fix",
			"package_name": "python-ecdsa",
			"product_name": "Red Hat OpenStack Platform 14 (Rocky)"
		},
		{
			"cpe": "cpe:/a:redhat:openstack:15",
			"fix_state": "Will not fix",
			"package_name": "python-ecdsa",
			"product_name": "Red Hat OpenStack Platform 15 (Stein)"
		},
		{
			"cpe": "cpe:/a:redhat:storage:3",
			"fix_state": "Affected",
			"package_name": "python-ecdsa",
			"product_name": "Red Hat Storage 3"
		},
		{
			"cpe": "cpe:/a:redhat:enterprise_linux:8::hypervisor",
			"fix_state": "Will not fix",
			"package_name": "python-ecdsa",
			"product_name": "Red Hat Virtualization 4"
		}
	],
	"public_date": "2019-09-26T00:00:00Z",
	"references": [
		"https://www.cve.org/CVERecord?id=CVE-2019-14853\nhttps://nvd.nist.gov/vuln/detail/CVE-2019-14853\nhttps://github.com/advisories/GHSA-pwfw-mgfj-7g3g"
	],
	"statement": "Although Red Hat OpenStack Platform ships the flawed code, RHOSP does not actually use python-ecdsa's functionality. As such, Red Hat OpenStack Platform will not be providing a fix for python-ecdsa at this time.\nCurrent releases of Red Hat Virtualization Manager no longer includes python-ecdsa as a dependency.  While it remains available in repositories as a legacy dependency, it is not installed by default and its use is not recommended.",
	"threat_severity": "Low",
	"upstream_fix": "python-ecdsa 0.13.3"
}
