{
	"name": "CVE-2016-10127",
	"threat_severity": "Moderate",
	"public_date": "2017-01-10T00:00:00Z",
	"bugzilla": {
		"description": "python-pysaml2: Vulnerable to XML external entity attack",
		"id": "1411794",
		"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1411794"
	},
	"cvss3": {
		"cvss3_base_score": "7.3",
		"cvss3_scoring_vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L",
		"status": "draft"
	},
	"cwe": "CWE-611",
	"details": [
		"PySAML2 allows remote attackers to conduct XML external entity (XXE) attacks via a crafted SAML XML request or response."
	],
	"statement": "This flaw resides in the XML Security Library (xmlsec1) and will be updated there; Red Hat OpenStack Platform is not affected.",
	"references": [
		"https://www.cve.org/CVERecord?id=CVE-2016-10127\nhttps://nvd.nist.gov/vuln/detail/CVE-2016-10127"
	],
	"package_state": [
		{
			"cpe": "cpe:/a:redhat:openstack:7",
			"fix_state": "Not affected",
			"package_name": "python-pysaml2",
			"product_name": "Red Hat Enterprise Linux OpenStack Platform 7 (Kilo)"
		},
		{
			"cpe": "cpe:/a:redhat:openstack:10",
			"fix_state": "Not affected",
			"package_name": "python-pysaml2",
			"product_name": "Red Hat OpenStack Platform 10 (Newton)"
		},
		{
			"cpe": "cpe:/a:redhat:openstack:11",
			"fix_state": "Not affected",
			"package_name": "python-pysaml2",
			"product_name": "Red Hat OpenStack Platform 11 (Ocata)"
		},
		{
			"cpe": "cpe:/a:redhat:openstack:8",
			"fix_state": "Not affected",
			"package_name": "python-pysaml2",
			"product_name": "Red Hat OpenStack Platform 8 (Liberty)"
		},
		{
			"cpe": "cpe:/a:redhat:openstack:9",
			"fix_state": "Not affected",
			"package_name": "python-pysaml2",
			"product_name": "Red Hat OpenStack Platform 9 (Mitaka)"
		}
	],
	"csaw": false
}
