{
	"name": "CVE-2021-23437",
	"threat_severity": "Moderate",
	"public_date": "2021-09-03T00:00:00Z",
	"bugzilla": {
		"description": "possible ReDoS via the getrgb function",
		"id": "2001907",
		"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2001907"
	},
	"cvss3": {
		"cvss3_base_score": "7.5",
		"cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
		"status": "draft"
	},
	"cwe": "CWE-400",
	"details": [
		"The package pillow 5.2.0 and before 8.3.2 are vulnerable to Regular Expression Denial of Service (ReDoS) via the getrgb function.",
		"A flaw was found in python-pillow, where a Regular Expression Denial of Service (ReDoS) via the getrgb function occurs. The highest threat from this vulnerability is to system availability."
	],
	"references": [
		"https://www.cve.org/CVERecord?id=CVE-2021-23437\nhttps://nvd.nist.gov/vuln/detail/CVE-2021-23437\nhttps://pillow.readthedocs.io/en/stable/releasenotes/8.3.2.html\nhttps://snyk.io/vuln/SNYK-PYTHON-PILLOW-1319443"
	],
	"package_state": [
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:7",
			"fix_state": "Not affected",
			"package_name": "python-pillow",
			"product_name": "Red Hat Enterprise Linux 7"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:8",
			"fix_state": "Not affected",
			"package_name": "python-pillow",
			"product_name": "Red Hat Enterprise Linux 8"
		},
		{
			"cpe": "cpe:/a:redhat:quay:3",
			"fix_state": "Affected",
			"impact": "moderate",
			"package_name": "quay/quay-rhel8",
			"product_name": "Red Hat Quay 3"
		}
	],
	"upstream_fix": "python-pillow 8.3.2",
	"csaw": false
}
