{
	"affected_release": [
		{
			"advisory": "RHSA-2009:1177",
			"cpe": "cpe:/o:redhat:enterprise_linux:4",
			"package": "python-0:2.3.4-14.7.el4_8.2",
			"product_name": "Red Hat Enterprise Linux 4",
			"release_date": "2009-07-27T00:00:00Z"
		},
		{
			"advisory": "RHSA-2009:1176",
			"cpe": "cpe:/o:redhat:enterprise_linux:5",
			"package": "python-0:2.4.3-24.el5_3.6",
			"product_name": "Red Hat Enterprise Linux 5",
			"release_date": "2009-07-27T00:00:00Z"
		}
	],
	"bugzilla": {
		"description": "CVE-2008-1721 python: integer signedness error in the zlib extension module",
		"id": "442005",
		"url": "https://bugzilla.redhat.com/show_bug.cgi?id=442005"
	},
	"csaw": false,
	"details": [
		"Integer signedness error in the zlib extension module in Python 2.5.2 and earlier allows remote attackers to execute arbitrary code via a negative signed integer, which triggers insufficient memory allocation and a buffer overflow."
	],
	"name": "CVE-2008-1721",
	"public_date": "2008-04-09T00:00:00Z",
	"references": [
		"https://www.cve.org/CVERecord?id=CVE-2008-1721\nhttps://nvd.nist.gov/vuln/detail/CVE-2008-1721"
	],
	"statement": "Red Hat is aware of this issue and is tracking it via the following bug: https://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=442005\nThe Red Hat Product Security has rated this issue as having low security impact, a future update may address this flaw. More information regarding issue severity can be found here: https://access.redhat.com/security/updates/classification/",
	"threat_severity": "Low"
}
